feat: package schema WIP
Automattic/newspack-popups pull request #1021
Opened 2022-12-02 17:57 UTC by leogermani

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-12-07 15:31 UTC, adekbadek requested changes
1. I've four prompts on a site, the output of the exporter lists the same error for each: `[options][utm_suppression] is not of type string.`. I've not edited this prompt option on any of these. 
2. I've one segment on a site. The export contains the following error for it: `created_at is not a valid property of Object.`
3. This feature is tricky to test without any interface. How about adding a simple WP CLI command, which would output a JSON-formatted string?

2022-12-07 15:31 UTC, adekbadek commented on includes/class-newspack-popups-exporter.php
> +		foreach ( $terms as $term ) {
For this line, the following warning is logged: `PHP Warning:  foreach() argument must be of type array|object, bool given`

2022-12-07 15:31 UTC, adekbadek commented on includes/class-newspack-popups-exporter.php
> +				$this->errors['segments'][ $stored_segment->term_id ] = $val->get_errors();
For this line, the following warning is logged: `PHP Warning:  Attempt to read property "term_id" on array`

2022-12-07 15:55 UTC, leogermani commented
Thanks for having a look! I'll check the points you raised

>     3. This feature is tricky to test without any user interface. How about adding a simple WP CLI command, which would output a JSON-formatted string?

Yes, that's the idea, I was planning to do this as the next PR, so they didn't get too big. But if you think it's a good idea we could it all in the same PR

2022-12-07 19:37 UTC, leogermani commented
@adekbadek I have added a simple CLI command and fixed the valdiation issues

2022-12-07 19:41 UTC, leogermani commented
I will look at the PHP warnings first thing tomorrow

2022-12-08 10:16 UTC, adekbadek requested changes
1. When running the command after pulling the branch, I got `Error: Callable "Newspack\\Campaigns\\CLI\\Export" does not exist, and cannot be registered as wp newspack-popups export` error, so I've ran `composer install`
2. Now it errors out with `Error: 'newspack-campaigns' is not a registered wp command. See 'wp help' for available commands.` 
3. The PR description should be updated with the testing instructions :)

2022-12-08 13:30 UTC, leogermani commented
@adekbadek Also please note that I just added a quick and simple command for not. Strings are not i18ned, we might think of a better name, example, parameters... this was just to help with testing

2022-12-08 14:22 UTC, adekbadek approved these changes
> I did [update PR description] yesterday! And included the composer install step.

Sorry, I see it now – I've got only my dysfunctional brain to blame! 

There's just one small change needed in the CLI command code comment.

2022-12-08 14:22 UTC, adekbadek commented on includes/cli/class-export.php
> +	 *     wp newspack-campaigns export --file=newspack-campaigns.json
> The command is newspack-popups and not newspack-campaigns

I was following the code comment, which should be updated: 

```suggestion
	 *     wp newspack-popups export --file=newspack-campaigns.json
```

2022-12-08 20:01 UTC, merged