fix: update no-padding popup styles
Automattic/newspack-popups pull request #1282
Opened 2024-03-06 21:27 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Right now, the Default and Hide Padding styles for the overlay prompts look the same. This PR makes the 'No Padding' style a true no padding style, but it's worth flagging that prior to this, that style has always had some padding.

I think it's naming/styling came from trying to be a popup variation of the inline prompt's no border style, but unlike removing the border and padding from the inline prompts, an overlay prompt with no padding and no blocks inside with padding looks broken:

![image](https://github.com/Automattic/newspack-popups/assets/177561/a7212090-55fe-4e34-b64f-9b1ee6f93ba8)

No padding also adds a lot of flexibility to the designs, but I'd appreciate some feedback around whether this seems like an okay trade off: 

![image](https://github.com/Automattic/newspack-popups/assets/177561/3f2c94fe-1206-4623-976a-f84cfcc4cfe4)

If we do opt to go with this, we should probably present it as something of a breaking change, as it'll change the appearance of this style in ways that may not work with live prompts that are using it.

See 1200550061930446-as-1206132801968396.

### How to test the changes in this Pull Request:

1. Create a new campaign prompt, and set it to display as an overlay. Give it some regular content.
2. Under the Styles panel on the right, set the prompt to have 'Hide Padding'.
3. Preview and note that the overlay popup has padding:

![image](https://github.com/Automattic/newspack-popups/assets/177561/c5fe0f93-871c-41cb-b9f0-0eae2de0a133)

4. Apply the PR and run `npm run build`.
5. Refresh the preview and confirm that the popup now has no padding: 

![image](https://github.com/Automattic/newspack-popups/assets/177561/bd4b5338-1507-4617-a954-52fe94f8b522)

6. Switch out the content blocks to add something a little more logical -- for example, a Cover Block, Media & Text Block, or Group block + padding as a base. Preview again and confirm this works well, and that there truly is no padding: 

![image](https://github.com/Automattic/newspack-popups/assets/177561/8ff8f1c9-bd9c-4477-b4e6-0ef42e01598d)

7. Test on smaller screen sizes, too, and make sure things look okay.
8. As part of this PR, I also added some styles to make sure the overlay always contrasts against the overlay when using the 'No Padding' style. To test this, try to change the overlay colour from a dark to a light colour, and confirm that the close button contrasts against it; test this with a few different colours:

![image](https://github.com/Automattic/newspack-popups/assets/177561/2e51a40a-e8d2-41a9-9062-77d48926972b)

9. Test this with the 'No Overlay' option, and confirm that the close button is black.
10. Switch the overlay back on and back to a dark colour, and test the Default and Large Styles for the overlay; confirm that the close button is black for both, even though it would be white for the Hide Padding style.
11. Add a featured image to the prompt; confirm that the button colour remains white, even when the overlay is light:

![image](https://github.com/Automattic/newspack-popups/assets/177561/e5b49883-472d-4c8c-a6f2-e71992cf6667)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-03-07 07:56 UTC, adekbadek commented
I think the offsetting of both the preview label and the close button are an issue now: 

<img width="134" alt="image" src="https://github.com/Automattic/newspack-popups/assets/7383192/ebc43fe2-766f-4108-af71-093cbaf10359">

<img width="80" alt="image" src="https://github.com/Automattic/newspack-popups/assets/7383192/ef564003-8423-4528-98b3-c15cdc3676ad">

@thomasguillot / @kevinzweerink – could you weight in here regarding the "no padding" styles? We need to find suitable placement for these two elements with the "no padding" style.

2024-03-07 10:33 UTC, thomasguillot commented
In https://github.com/Automattic/newspack-popups/pull/1282/commits/e7f1fa78727db90a7aaeefe183afdf3a536ffc7f I slightly tweaked the position of the "Preview" label

![Screenshot 2024-03-07 at 10 32 31@2x](https://github.com/Automattic/newspack-popups/assets/177929/df2e0e10-6899-4afc-8938-f3ca52ec2358)

2024-03-07 10:35 UTC, thomasguillot commented
For the close button, the position doesn't bother me as much. But I wonder what @kevinzweerink thinks about this.

2024-03-07 14:30 UTC, kevinzweerink commented
Close button looks good to me! @thomasguillot 's change to the preview label looks right too.

2024-03-08 07:58 UTC, adekbadek requested changes
> If we do opt to go with this, we should probably present it as something of a breaking change, as it'll change the appearance of this style in ways that may not work with live prompts that are using it.

It's a breaking change indeed, even if it fixes the feature. 

I'm in favour of not making it a breaking change – in order to avoid migration and unnecessary support burden.
As suggested on Asana, let's call this "old" option "Small Padding", and add a _real_ "Hide Padding" option.

2025-01-08 20:04 UTC, laurelfulford commented
Closing this PR in favour of a reworked version that doesn't include breaking changes 🙂

2025-01-08 20:04 UTC, closed without merging