Handle referrer segmentation
Automattic/newspack-popups pull request #323
Opened 2020-11-26 12:45 UTC by adekbadek

### All Submissions:

* [X] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds handling of a referrer-based segment.

### How to test the changes in this Pull Request:

1. Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/708

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2020-11-30 04:17 UTC, jeffersonrabb reviewed
I'm having trouble getting the testing to work. Do I understand correctly that the line referenced in the testing instructions should be changed to:

```
$popups_access_provider['authorization'] .= '&ref=google.com';
```

2020-11-30 10:22 UTC, adekbadek commented
Yes, but it has to be a full (parsable) URL, like

```
$popups_access_provider['authorization'] .= '&ref=https://google.com';
```

2020-11-30 23:20 UTC, jeffersonrabb requested changes

2020-11-30 23:20 UTC, jeffersonrabb commented on api/campaigns/class-maybe-show-campaign.php
> +					explode( ',', $campaign_segment->referrers )
```suggestion
					array_map( 'trim', explode( ',', $campaign_segment->referrers ) )
```

Fixes issue if there are spaces around the commas, e.g. `google.com, facebook.com`.

2020-12-01 19:15 UTC, jeffersonrabb approved these changes

2020-12-01 22:18 UTC, merged