feat: deprecate test mode and never frequency
Automattic/newspack-popups pull request #390
Opened 2021-01-12 15:11 UTC by jeffersonrabb

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-01-13 13:05 UTC, adekbadek requested changes
As for the migration strategy, WDYT about simply 
1. marking `test` & `never` popups as inactive [in the wizard](https://github.com/Automattic/newspack-plugin/pull/809)
2. filtering these so they are never shown to a reader
?

2021-01-13 13:51 UTC, jeffersonrabb commented on includes/class-newspack-popups.php
> +				$dismiss_text = null;
Inline campaigns generally don't need permanent dismissal buttons. That feature is really only required for intrusive campaigns like pop-ups.

2021-01-13 14:20 UTC, adekbadek commented on includes/class-newspack-popups.php
> +				$dismiss_text = null;
True, I forgot that an empty message will hide the button 👍

2021-01-18 22:20 UTC, dkoo commented
> As for the migration strategy, WDYT about simply
> 
> 1. marking `test` & `never` popups as inactive [in the wizard](https://github.com/Automattic/newspack-plugin/pull/809)
> 2. filtering these so they are never shown to a reader
>    ?

Since we've simplified campaign statuses to published vs. unpublished, what if we were to programmatically unpublish any "test" and "never" campaigns that are found and treat them the same as draft campaigns?

2021-01-19 00:34 UTC, jeffersonrabb commented on includes/class-newspack-popups-inserter.php
>  		}
Done in https://github.com/Automattic/newspack-popups/pull/390/commits/6ef265b9fa6d061d1f421a7e70f72e94aa2fcf2d

2021-01-19 00:41 UTC, jeffersonrabb commented on src/editor/StatusSidebar.js
> -				/>
Fixed in https://github.com/Automattic/newspack-popups/pull/390/commits/a4ee3e057c5f1793c1bb2a28e0c8a5061f4ad75b

2021-01-19 02:52 UTC, jeffersonrabb commented
> Since we've simplified campaign statuses to published vs. unpublished, what if we were to programmatically unpublish any "test" and "never" campaigns that are found and treat them the same as draft campaigns?
> 
> Edit to add: On the front-end, we should still filter any `test` or `never` campaigns so they're never shown, as a failsafe.

This is now the case, implemented (mostly) in https://github.com/Automattic/newspack-popups/pull/390/commits/72f99434eaa149416b73ec55762127fd7e8bba33. Complete explanation and testing instructions in https://github.com/Automattic/newspack-plugin/pull/809.

2021-01-19 12:27 UTC, adekbadek requested changes

2021-01-19 12:47 UTC, jeffersonrabb commented on includes/class-newspack-popups-inserter.php
>  		// Hide non-test mode campaigns for logged-in users.
Fixed in https://github.com/Automattic/newspack-popups/pull/390/commits/c8c76eae3e3649ff428969424ca069fde8fa2a2e

2021-01-19 12:47 UTC, jeffersonrabb commented on src/editor/StatusSidebar.js
> +		isOverlay && (
Fixed in https://github.com/Automattic/newspack-popups/pull/390/commits/c8c76eae3e3649ff428969424ca069fde8fa2a2e

2021-01-19 15:56 UTC, adekbadek approved these changes

2021-01-19 17:02 UTC, dkoo approved these changes
The migration works great and the test/never campaigns are properly unpublished and don't appear in preview or on the front-end.

2021-01-19 17:17 UTC, merged