Handle setting donor status by visiting a page
Automattic/newspack-popups pull request #408
Opened 2021-01-21 16:55 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #377 .

### How to test the changes in this Pull Request:

_Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/829_

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-01-26 20:59 UTC, dkoo approved these changes
Looks good and works as described. Just a small suggestion on the help text for the new Settings option.

2021-01-26 20:59 UTC, dkoo commented on includes/class-newspack-popups-settings.php
> +					'When using an off-site donation platform, you can set it to landing to a page on your site. When a reader is landinged to this page, they will be marked as a donor.',
```suggestion
					'Set a page on your site as a donation landing page. Once a reader views this page, they will be considered a donor. This is helpful if you're using an off-site donation platform but still want to target donors as an audience segment.',
```

2021-01-26 21:00 UTC, dkoo requested changes
Whoops, approved by accident. Requesting changes.

2021-01-27 10:56 UTC, adekbadek commented on includes/class-newspack-popups-settings.php
> +					'When using an off-site donation platform, you can set it to landing to a page on your site. When a reader is landinged to this page, they will be marked as a donor.',
"landinged" 😂  🤦‍♂️

2021-01-28 18:05 UTC, dkoo approved these changes

2021-01-28 18:31 UTC, merged