feat: improved duplication UI via modal
Automattic/newspack-popups pull request #564
Opened 2021-06-18 17:45 UTC by dkoo

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-06-21 11:43 UTC, thomasguillot approved these changes
@dkoo, I pushed a few changes: https://github.com/Automattic/newspack-popups/pull/564/commits/e8a5cf81b446b685768f4325b52bec0bc35a7e88

2021-06-21 13:41 UTC, thomasguillot commented
> do you have any ideas about why the @wordpress/icons package seems to not be importable when Newspack Components are imported as an NPM package? If we can solve this bug, we can switch the components here to Newspack Components instead of core.

I don't know why it crashes but we should be using Core components in the editor anyway.

2021-06-23 20:42 UTC, dkoo commented
@thomasguillot Changes look good, thanks!

2021-06-29 08:16 UTC, adekbadek requested changes

2021-06-29 08:16 UTC, adekbadek commented on src/editor/Duplicate.js
> +									{ __( 'This prompt will be unassigned.', 'newspack-popups' ) }
Just to make it more understandable:

```suggestion
									{ __( 'The new prompt will no be assigned to any campaign.', 'newspack-popups' ) }
```

2021-06-29 08:16 UTC, adekbadek commented on src/editor/Duplicate.js
> +									{ __( 'The prompt is currently unassigned.', 'newspack-popups' ) }
WDYT think about demystifying "unassigned" a bit:

```suggestion
									{ __( 'This prompt is currently not assigned to any campaign.', 'newspack-popups' ) }
```

2021-06-30 15:27 UTC, dkoo commented on src/editor/Duplicate.js
> +									{ __( 'This prompt will be unassigned.', 'newspack-popups' ) }
Good suggestion! Updated in d40359b.

2021-06-30 18:08 UTC, adekbadek approved these changes

2021-06-30 18:10 UTC, merged