Fix/naming duplicated prompts
Automattic/newspack-popups pull request #706
Opened 2021-11-30 08:09 UTC by kariae

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #628.

### How to test the changes in this Pull Request:

1. Create a prompt from the campaigns screen with `My Prompt` as a title.
2. Duplicate the prompt and notice that the suggested name is correct and should be `My Prompt copy`.
3. Duplicate again the first prompt and change its title this time to `Second Prompt`.
4. Duplicate the `Second Prompt`, and notice that the title generated `My Prompt copy 2` is based on the original prompt and not the parent prompt.
5. Check out this PR.
6. Duplicate the first prompt and change its name to `Third Prompt`.
7. Duplicate `Third Prompt` and notice that this time, the title generated `Third Prompt copy` is based on the parent prompt.
8. Duplicate `Third Prompt` or `Third Prompt copy` and notice that the suggested title `Third Prompt copy 2` is based on the parent title and the total number of occurrences.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-12-03 22:45 UTC, dkoo requested changes
I don't think the iterator is working as expected. Here's what I saw:

- [x] **Duplicating a prompt named `My Prompt`:** The suggested title is `My Prompt copy`, as expected.
- [ ] **Duplicating `My Prompt copy`:** The suggested title is `My Prompt copy copy`
  - **Expected:** I would expect the suggested title to be `My Prompt copy 2`. If there's already a prompt named `My Prompt copy 2`, I would expect `My Prompt copy 3` and so on.
- [ ] **Duplicating `My Prompt` again:** The suggested title is once again `My Prompt copy` despite there already being a prompt with that title.
  - **Expected:** I'd expect the suggested title to be `My Prompt copy 2` (or `3`, etc.) if there are already other prompts with the same title.

2021-12-03 22:45 UTC, dkoo commented on includes/class-newspack-popups.php
> +					'duplicate_of' => empty( $title ) || preg_match( "/^$original_title_base\s*\d*$/", $title )
If we're solely basing the copy titles off of the name of the prompt being copied (whether or not it is itself a duplicate) plus the existence of other prompts with the same title, I believe we might be able to deprecate the `duplicate_of` meta field, right?

2021-12-06 22:39 UTC, dkoo approved these changes
My mistake! This works from both the editor screen and from the Campaigns dashboard in combo with https://github.com/Automattic/newspack-plugin/pull/1326. Suggested titles increment as expected if there were other prompts with the same `copy` name.

I see how you're using `duplicate_of` to query other copies of the same original prompt before incrementing the suggested title. This works well, but it does present an unlikely edge case where if you have two prompts with the same title that aren't duplicates of each other, duplicating each will result in the same suggested titles. But this is such an edge case that I'm okay with it.

2021-12-09 09:39 UTC, kariae commented
Thank you @dkoo for the review and feedback.

Yes, I'm using `duplicate_of` exactly as you described, and I had in mind that edge case, that technically is possible, but in the day to day usage we 99% won't have 😅

2021-12-09 09:41 UTC, merged