feat: add a filter for supported post types
Automattic/newspack-popups pull request #726
Opened 2021-12-07 18:03 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Applies a filter to the array of supported post types to allow other plugins to add Campaigns support for their own post types. Fixes some unexpected behavior that @kariae and I debugged together when trying to display an archive prompt on a category archive page that contained both posts and listings.

### How to test the changes in this Pull Request:

See https://github.com/Automattic/newspack-listings/pull/157 and https://github.com/Automattic/newspack-newsletters/pull/640 for testing instructions.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-12-08 15:22 UTC, miguelpeixe requested changes
If we expect Campaigns to work on every public post type with archive support, perhaps the [`get_post_types()` function](https://developer.wordpress.org/reference/functions/get_post_types/) is a more generic solution. What do you think?

I still think the filter is useful for odd cases, but the function arguments would be something like:

```php
get_post_types( array(
	'public'      => true,
	'has_archive' => true,
) );
```

2021-12-08 16:32 UTC, dkoo commented
> If we expect Campaigns to work on every public post type with archive support, perhaps the [`get_post_types()` function](https://developer.wordpress.org/reference/functions/get_post_types/) is a more generic solution. What do you think?

That's actually open for discussion. I implemented the filter to handle public post types that can appear alongside posts on _post_ archives (not just their own archives), which for our purposes are newsletters and listings. Defaulting to showing prompts on any post type archive would be one step further but would also mean we don't need the extra changes in the Newsletters and Listings plugins. @adekbadek @kariae what do you guys think?

2021-12-08 16:43 UTC, yogeshbeniwal commented
@dkoo If we can keep it generic for showing prompts on any post type archive, that will be better. Like some publishers has series archives etc. This will save individual PR to add more supported post types.

2021-12-09 09:33 UTC, kariae commented
I think having Campaigns working on all public post types with archive support is the way to go, so a 👍 for using `get_post_types`. In case we need an exclude filter we can add it the same as [we did for tags and categories](https://github.com/Automattic/newspack-popups/pull/641).

2021-12-09 17:50 UTC, dkoo commented
@Automattic/newspack-product cc @yogeshbeniwal Thanks to all for your input! I've implemented the filter with `get_post_types` as suggested, so now by default Campaigns will support posts, pages, and all public CPTs with post type archives. I kept the filter in place so it can still be used to remove or otherwise edit the list of post types, but this should eliminate the need to add support for CPTs in other plugins.

2021-12-14 15:16 UTC, miguelpeixe approved these changes

2021-12-14 22:26 UTC, merged