fix: make "scroll" the default inline trigger_type
Automattic/newspack-popups pull request #846
Opened 2022-04-12 20:57 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes an edge case where an inline prompt can get stuck with an invalid "insertion position" or `trigger_type` value, which causes the `RangeControl` used to set the insertion position to not appear at all in the editor, and the prompt to always appear at the very end of the content.

Prior to #755 `scroll` was really the only valid `trigger_type` value for inline prompts, so all inline prompts behaved the same way regardless of what that value was. After #842, a second `blocks_count` option was added, but it's still possible for a prompt to be saved as an overlay, then converted to an inline prompt, and have `trigger_type` be set to `time` as a result. This is the edge case fixed by this PR. The fix is to make any value other than `blocks_count` behave like `scroll`, effectively making this the default/fallback behavior.

Closes #842.

### How to test the changes in this Pull Request:

1. Publish an overlay prompt with the "Trigger" option set to "Timer".
2. After the post is saved, change the "Prompt Type" to "Inline". This puts the the prompt into a state where it's inserted as an inline prompt, but its `trigger_type` value is still set to `time`, an invalid value for inline prompts.
3. On `master`, in the editor under the "Prompt Settings" sidebar, observe that the `RangeControl` to set the precise insertion position is not rendered at all.
4. On the front-end, observe that the prompt gets inserted like an inline prompt at the end of every article.
5. Check out this branch. Confirm that in the editor, the "Insertion Position" is set to "Scroll" and the `RangeControl` appears with the default value of 30%.
6. Confirm on the front-end that the prompt gets inserted at 30% of the content, which is the default inline prompt behavior.
7. Conversely, set the "Insertion Position" option to "Blocks Count" and save, then convert the "Prompt Type" to an Overlay. This puts the prompt into a state where it's an overlay with a `trigger_type` of `blocks_count`, an invalid value for overlays.
8. Confirm that in the editor, the "Trigger" is shown as the default value "Timer".
9. Confirm on the front-end that the overlay appears after a 3 second delay, the default delay.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-04-13 20:20 UTC, miguelpeixe requested changes
It's working perfectly for switching from overlay to inline.

After saving the inline prompt to use "block count" and switching back to overlay, the "Trigger" select displays "Time" but I'm unable to select the time and the overlay prompt does not render on the frontend:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/820752/163263299-f8f415e6-a893-41a7-b98f-e2ada929577e.png">

The delay `RangeControl` does appear if I change the trigger options manually after selecting overlay.

2022-04-13 21:21 UTC, dkoo commented
> After saving the inline prompt to use "block count" and switching back to overlay, the "Trigger" select displays "Time" but I'm unable to select the time

Ah, good catch—this required the same fix for making the default trigger type "Timer" for overlays: ccd8827

> and the overlay prompt does not render on the frontend

This wasn't the case for me, at least when I viewed it in a new incognito window. Overlays can only be shown with "Once" or "Once per day" frequency, so if you viewed that prompt as an inline prompt, converted it to overlay, then tried to view it again, it would be dismissed as already seen. Can you confirm that you see the overlay in a new session after converting from inline to overlay?

2022-04-14 13:59 UTC, miguelpeixe commented
Thank you for revisign! Switching prompt types now behave as expected! 💯 

> This wasn't the case for me, at least when I viewed it in a new incognito window. 

Yep! Must've been the frequency config.

2022-04-14 13:59 UTC, miguelpeixe approved these changes

2022-04-14 15:21 UTC, merged